In [12]:
import numpy as np

# Define the image array
image_array = np.array([
    [52, 55, 59, 52, 55],
    [55, 59, 52, 59, 59],
    [55, 52, 52, 55, 55],
    [59, 59, 59, 52, 55],
    [52, 55, 55, 59, 59]
])

# Flatten the image array to a 1D array
flattened_array = image_array.flatten()

# Calculate the histogram
hist, _ = np.histogram(flattened_array, bins=256, range=(0, 255))

In [14]:
print("Original Image Array:")
print(image_array)
print("\nFlattened Array")
print(flattened_array)

Original Image Array:
[[52 55 59 52 55]
 [55 59 52 59 59]
 [55 52 52 55 55]
 [59 59 59 52 55]
 [52 55 55 59 59]]

Flattened Array
[52 55 59 52 55 55 59 52 59 59 55 52 52 55 55 59 59 59 52 55 52 55 55 59
 59]
